events {}

http {

    ####################################################################
    # HTTP SERVER (80)
    ####################################################################
    server {

        listen 80;
        server_name abjms.duckdns.org;

        # Let's Encrypt Challenge
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirect everything else to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    ####################################################################
    # HTTPS SERVER (443)
    ####################################################################
    server {

        listen 443 ssl http2;
        server_name abjms.duckdns.org;

        ###############################################################
        # SSL Certificates
        ###############################################################
        ssl_certificate /etc/letsencrypt/live/abjms.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/abjms.duckdns.org/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        ###############################################################
        # Eureka Dashboard
        ###############################################################
        location /eureka/ {

            proxy_pass http://service-registry:8761/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            proxy_redirect / /eureka/;

            sub_filter_types text/html;
            sub_filter_once off;
            sub_filter 'href="/' 'href="/eureka/';
            sub_filter 'src="/'  'src="/eureka/';
        }

        ###############################################################
        # Department Service
        ###############################################################
        location /department/ {

            proxy_pass http://department-service:9001/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        ###############################################################
        # User Service
        ###############################################################
        location /user/ {

            proxy_pass http://user-service:9002/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

    }

}